import io
import logging
import os

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import Response
from PIL import Image
from sqlalchemy.sql import select

from app.services.cache_service import (
    alias_redirect_cache_control_header,
    cache_control_header,
    immutable_asset_cache_control_header,
    weak_etag_from_body,
)
from app.services.static_map_service import StaticMapService
from db.models import resources

logger = logging.getLogger(__name__)

router = APIRouter()

ASSET_CACHE_TTL_SECONDS = int(os.getenv("ASSET_CACHE_TTL_SECONDS", "3600"))


async def _fetch_resource_dict(resource_id: str) -> dict | None:
    """Load a resource row for static map asset generation."""
    from app.api.v1.endpoint_modules.resources.static_map import async_session

    async with async_session() as session:
        query = select(resources).where(resources.c.id == resource_id)
        result = await session.execute(query)
        row = result.fetchone()
        if not row:
            return None
        return dict(row._mapping)


def _resource_geometry(resource_dict: dict) -> object | None:
    """Return the geometry input currently used for static-map generation."""
    return resource_dict.get("locn_geometry") or resource_dict.get("dcat_bbox")


def _validated_static_asset_response(
    asset_data: bytes,
    request: Request,
    *,
    cache_control: str | None = None,
    etag: str | None = None,
) -> Response:
    """Return a cacheable PNG or SVG response after validating the cached/generated bytes."""
    media_type: str
    stripped = asset_data.lstrip()

    if asset_data.startswith(b"\x89PNG\r\n\x1a\n"):
        try:
            img = Image.open(io.BytesIO(asset_data))
            img.verify()
        except Exception as e:
            logger.error(
                "Cached PNG asset is invalid: %s. First 200 bytes: %r",
                e,
                asset_data[:200],
            )
            raise HTTPException(
                status_code=404,
                detail="Invalid image data in cache. This may indicate corrupted cache entry.",
            ) from None
        media_type = "image/png"
    elif stripped.startswith(b"<svg") or (
        stripped.startswith(b"<?xml") and b"<svg" in stripped[:512]
    ):
        try:
            stripped.decode("utf-8")
        except UnicodeDecodeError as e:
            logger.error(
                "Cached SVG asset is invalid: %s. First 200 bytes: %r",
                e,
                asset_data[:200],
            )
            raise HTTPException(
                status_code=404,
                detail="Invalid SVG data in cache. This may indicate corrupted cache entry.",
            ) from None
        media_type = "image/svg+xml"
    else:
        logger.error(
            "Cached static asset has unsupported format. First 200 bytes: %r",
            asset_data[:200],
        )
        raise HTTPException(
            status_code=404,
            detail="Unsupported cached asset format.",
        ) from None

    etag = etag or weak_etag_from_body(asset_data)
    headers = {
        "ETag": etag,
        "Cache-Control": cache_control or cache_control_header(ttl_seconds=ASSET_CACHE_TTL_SECONDS),
        "Content-Disposition": "inline",
        "Vary": "Accept-Encoding",
    }

    inm = request.headers.get("if-none-match")
    if inm and inm == etag:
        return Response(status_code=304, headers=headers)

    return Response(content=asset_data, media_type=media_type, headers=headers)


async def _get_asset_redirect(
    resource_id: str,
    *,
    variant: str,
    source_signature: str | None = None,
) -> Response | None:
    """Redirect resource-id static map requests to a hot immutable asset when possible."""
    map_service = StaticMapService()
    map_hash = await map_service.materialize_cached_variant(
        resource_id,
        variant=variant,
        source_signature=source_signature,
        hydrate_asset=False,
    )
    if not map_hash:
        return None

    return Response(
        status_code=302,
        headers={
            "Location": f"/api/v1/static-map-assets/{map_hash}",
            "Cache-Control": alias_redirect_cache_control_header(),
        },
    )


async def _get_or_generate_map_data(
    resource_id: str,
    *,
    resource_dict: dict,
    variant: str,
    source_signature: str,
) -> bytes:
    """Return the requested static map variant, generating it synchronously when needed."""
    geometry = _resource_geometry(resource_dict)
    map_service = StaticMapService()

    if variant == "geometry":
        map_data = await map_service.get_cached_map(
            resource_id,
            source_signature=source_signature,
        )
        if not map_data:
            map_data = (
                map_service.generate_map(
                    resource_id,
                    geometry,
                    source_signature=source_signature,
                )
                if geometry
                else map_service.generate_global_map(
                    resource_id,
                    source_signature=source_signature,
                )
            )
        if not map_data:
            map_data = map_service.generate_global_map(
                resource_id,
                source_signature=source_signature,
            )
        if not map_data:
            raise HTTPException(status_code=404, detail="Static map not found")
        return map_data

    if variant == "basemap":
        map_data = await map_service.get_cached_basemap(
            resource_id,
            source_signature=source_signature,
        )
        if not map_data:
            map_data = (
                map_service.generate_basemap(
                    resource_id,
                    geometry,
                    source_signature=source_signature,
                )
                if geometry
                else map_service.generate_global_basemap(
                    resource_id,
                    source_signature=source_signature,
                )
            )
        if not map_data:
            map_data = map_service.generate_global_basemap(
                resource_id,
                source_signature=source_signature,
            )
        if not map_data:
            raise HTTPException(status_code=404, detail="Static map not found")
        return map_data

    raise HTTPException(status_code=400, detail="Unsupported static map variant")


@router.get("/static-maps/institutions/{map_id}")
async def get_institution_static_map(
    map_id: str,
    request: Request,
    lat: float,
    lon: float,
    zoom: int = 15,
):
    """Serve or generate a cached campus-centered static basemap image."""
    cache_id = f"institution:{map_id}"
    try:
        map_service = StaticMapService(map_width=640, map_height=320)
        source_signature = map_service.centered_basemap_signature(
            latitude=lat,
            longitude=lon,
            zoom=zoom,
        )
        map_data = await map_service.get_cached_basemap(
            cache_id,
            source_signature=source_signature,
        )
        if not map_data:
            map_data = map_service.generate_centered_basemap(
                cache_id,
                latitude=lat,
                longitude=lon,
                zoom=zoom,
                source_signature=source_signature,
            )
    except Exception as e:
        logger.error(f"Error retrieving institution static map {map_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e)) from e

    if not map_data:
        raise HTTPException(status_code=404, detail="Institution static map not found")

    return _validated_static_asset_response(map_data, request)


@router.get("/static-map-assets/{map_hash}")
async def get_static_map_asset(map_hash: str, request: Request):
    """Serve a hash-addressed immutable static map or icon asset directly from Redis."""
    map_service = StaticMapService()
    map_data = await map_service.get_cached_asset(map_hash)
    if not map_data:
        raise HTTPException(status_code=404, detail="Static map asset not found")

    return _validated_static_asset_response(
        map_data,
        request,
        cache_control=immutable_asset_cache_control_header(),
        etag=f'W/"{map_hash}"',
    )


@router.get("/static-maps/{resource_id}/geometry")
async def get_static_map_geometry(resource_id: str, request: Request):
    """Serve or generate the static map with geometry overlay for a resource."""
    map_service = StaticMapService()
    redirect = await _get_asset_redirect(
        resource_id,
        variant=map_service.geometry_variant(),
    )
    if redirect is not None:
        return redirect

    resource_dict = await _fetch_resource_dict(resource_id)
    if not resource_dict:
        raise HTTPException(status_code=404, detail="Resource not found")

    source_signature = map_service.geometry_signature(_resource_geometry(resource_dict))
    redirect = await _get_asset_redirect(
        resource_id,
        variant=map_service.geometry_variant(),
        source_signature=source_signature,
    )
    if redirect is not None:
        return redirect

    try:
        map_data = await _get_or_generate_map_data(
            resource_id,
            resource_dict=resource_dict,
            variant="geometry",
            source_signature=source_signature,
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving static map geometry {resource_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e)) from e

    return _validated_static_asset_response(map_data, request)


@router.get("/static-maps/{resource_id}/resource-class-icon")
async def get_static_map_resource_class_icon(resource_id: str):
    """Serve the resource-class icon over the basemap background."""
    redirect = await _get_asset_redirect(
        resource_id,
        variant="resource-class-icon",
    )
    if redirect is not None:
        return redirect

    resource_dict = await _fetch_resource_dict(resource_id)
    if not resource_dict:
        raise HTTPException(status_code=404, detail="Resource not found")

    try:
        from app.api.v1.endpoint_modules.resources.thumbnail import (
            _resource_class_icon_signature,
            _svg_icon_bytes_for_resource,
        )

        variant = "resource-class-icon"
        source_signature = _resource_class_icon_signature(
            resource_dict,
            variant="icon-basemap",
        )
        redirect = await _get_asset_redirect(
            resource_id,
            variant=variant,
            source_signature=source_signature,
        )
        if redirect is not None:
            return redirect

        svg_bytes = await _svg_icon_bytes_for_resource(
            resource_dict,
            variant="icon-basemap",
        )
        map_service = StaticMapService()
        map_hash = await map_service.materialize_asset(
            resource_id,
            variant=variant,
            map_bytes=svg_bytes,
            source_signature=source_signature,
        )
        if map_hash:
            return Response(
                status_code=302,
                headers={
                    "Location": f"/api/v1/static-map-assets/{map_hash}",
                    "Cache-Control": alias_redirect_cache_control_header(),
                },
            )

        return Response(
            content=svg_bytes,
            media_type="image/svg+xml",
            headers={"Cache-Control": "no-store"},
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving static map icon asset {resource_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e)) from e


@router.get("/static-maps/{resource_id}")
async def get_static_map(resource_id: str, request: Request):
    """Serve or generate the basemap-only static map asset for a resource."""
    map_service = StaticMapService()
    redirect = await _get_asset_redirect(
        resource_id,
        variant=map_service.basemap_variant(),
    )
    if redirect is not None:
        return redirect

    resource_dict = await _fetch_resource_dict(resource_id)
    if not resource_dict:
        raise HTTPException(status_code=404, detail="Resource not found")

    source_signature = map_service.geometry_signature(_resource_geometry(resource_dict))
    redirect = await _get_asset_redirect(
        resource_id,
        variant=map_service.basemap_variant(),
        source_signature=source_signature,
    )
    if redirect is not None:
        return redirect

    try:
        map_data = await _get_or_generate_map_data(
            resource_id,
            resource_dict=resource_dict,
            variant="basemap",
            source_signature=source_signature,
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving basemap static map {resource_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e)) from e

    return _validated_static_asset_response(map_data, request)
