// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/resources/:id": {
    params: {
      "id": string;
    };
  };
  "/resources/:id/static-map": {
    params: {
      "id": string;
    };
  };
  "/resources/:id/static-map/no-cache": {
    params: {
      "id": string;
    };
  };
  "/resources/:id/thumbnail": {
    params: {
      "id": string;
    };
  };
  "/resources/:id/thumbnail/no-cache": {
    params: {
      "id": string;
    };
  };
  "/thumbnails/placeholder": {
    params: {};
  };
  "/thumbnails/:image_hash": {
    params: {
      "image_hash": string;
    };
  };
  "/iiif/manifest": {
    params: {};
  };
  "/suggest": {
    params: {};
  };
  "/search/facets/:facetName": {
    params: {
      "facetName": string;
    };
  };
  "/map/h3": {
    params: {};
  };
  "/bookmarks": {
    params: {};
  };
  "/map": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/test/fixtures": {
    params: {};
  };
  "/test/fixtures/providers": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/resources/:id" | "/resources/:id/static-map" | "/resources/:id/static-map/no-cache" | "/resources/:id/thumbnail" | "/resources/:id/thumbnail/no-cache" | "/thumbnails/placeholder" | "/thumbnails/:image_hash" | "/iiif/manifest" | "/suggest" | "/search/facets/:facetName" | "/map/h3" | "/bookmarks" | "/map" | "/test" | "/test/fixtures" | "/test/fixtures/providers" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/resources.$id.tsx": {
    id: "routes/resources.$id";
    page: "/resources/:id";
  };
  "routes/resources.$id.static-map.ts": {
    id: "routes/resources.$id.static-map";
    page: "/resources/:id/static-map";
  };
  "routes/resources.$id.static-map.no-cache.ts": {
    id: "routes/resources.$id.static-map.no-cache";
    page: "/resources/:id/static-map/no-cache";
  };
  "routes/resources.$id.thumbnail.ts": {
    id: "routes/resources.$id.thumbnail";
    page: "/resources/:id/thumbnail";
  };
  "routes/resources.$id.thumbnail.no-cache.ts": {
    id: "routes/resources.$id.thumbnail.no-cache";
    page: "/resources/:id/thumbnail/no-cache";
  };
  "routes/thumbnails.placeholder.ts": {
    id: "routes/thumbnails.placeholder";
    page: "/thumbnails/placeholder";
  };
  "routes/thumbnails.$image_hash.ts": {
    id: "routes/thumbnails.$image_hash";
    page: "/thumbnails/:image_hash";
  };
  "routes/iiif.manifest.ts": {
    id: "routes/iiif.manifest";
    page: "/iiif/manifest";
  };
  "routes/suggest.ts": {
    id: "routes/suggest";
    page: "/suggest";
  };
  "routes/api.search.facets.ts": {
    id: "routes/api.search.facets";
    page: "/search/facets/:facetName";
  };
  "routes/api.map.h3.ts": {
    id: "routes/api.map.h3";
    page: "/map/h3";
  };
  "routes/bookmarks.tsx": {
    id: "routes/bookmarks";
    page: "/bookmarks";
  };
  "routes/map.tsx": {
    id: "routes/map";
    page: "/map";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/test.fixtures.tsx": {
    id: "routes/test.fixtures";
    page: "/test/fixtures";
  };
  "routes/test.fixtures.providers.tsx": {
    id: "routes/test.fixtures.providers";
    page: "/test/fixtures/providers";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/resources.$id": typeof import("./app/routes/resources.$id.tsx");
  "routes/resources.$id.static-map": typeof import("./app/routes/resources.$id.static-map.ts");
  "routes/resources.$id.static-map.no-cache": typeof import("./app/routes/resources.$id.static-map.no-cache.ts");
  "routes/resources.$id.thumbnail": typeof import("./app/routes/resources.$id.thumbnail.ts");
  "routes/resources.$id.thumbnail.no-cache": typeof import("./app/routes/resources.$id.thumbnail.no-cache.ts");
  "routes/thumbnails.placeholder": typeof import("./app/routes/thumbnails.placeholder.ts");
  "routes/thumbnails.$image_hash": typeof import("./app/routes/thumbnails.$image_hash.ts");
  "routes/iiif.manifest": typeof import("./app/routes/iiif.manifest.ts");
  "routes/suggest": typeof import("./app/routes/suggest.ts");
  "routes/api.search.facets": typeof import("./app/routes/api.search.facets.ts");
  "routes/api.map.h3": typeof import("./app/routes/api.map.h3.ts");
  "routes/bookmarks": typeof import("./app/routes/bookmarks.tsx");
  "routes/map": typeof import("./app/routes/map.tsx");
  "routes/test": typeof import("./app/routes/test.tsx");
  "routes/test.fixtures": typeof import("./app/routes/test.fixtures.tsx");
  "routes/test.fixtures.providers": typeof import("./app/routes/test.fixtures.providers.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};