export const CONFIGURED_FACETS = [
  'year_histogram',
  'dct_spatial_sm',
  'time_period',
  'gbl_resourceClass_sm',
  'gbl_resourceType_sm',
  'gbl_indexyear_im',
  'b1g_language_sm',
  'dct_creator_sm',
  'dct_publisher_sm',
  'schema_provider_s',
  'dct_accessRights_s',
  'gbl_georeferenced_b',
  'b1g_georeferenced_allmaps_b',
] as const;
